// Cycle 31: hand-curated "personality" jobs. Each entry has a quirk
// (one-word hook), a signature outfit (cosmetic string until C35 pixel
// art lands), an 80-150 字 bio, and 1-2 unique skills that aren't drawn
// from the procedural pool.
//
// Phase 1 (this file): 12 curated jobs across the 8 main categories.
// Phase 2 (Cycle 31-d): bulk-generate ~90 more via the AI pipeline
// described in docs/team/CURATED_JOB_BULK.md.

export type CuratedSkill = {
  name: string;
  description: string;
  type: "attack" | "heal" | "buff" | "debuff" | "special";
  element: string | null;
  power: number;
  cost: number;
  cooldown?: number;
  targetType?: string;
};

export type CuratedJob = {
  name: string;
  category: "warrior" | "mage" | "rogue" | "cleric" | "craft" | "support" | "heretic" | "rare";
  rank: "beginner" | "intermediate" | "advanced" | "special" | "legendary";
  description: string;
  quirk: string;
  signatureOutfit: string;
  signatureBio: string;
  baseStats: {
    hp: number;
    mp: number;
    atk: number;
    def: number;
    mat: number;
    mdf: number;
    spd: number;
  };
  uniqueSkills: CuratedSkill[];
};

export const CURATED_JOBS: CuratedJob[] = [
  // ---------- WARRIOR ----------
  {
    name: "眼鏡戦士",
    category: "warrior",
    rank: "intermediate",
    description: "丸眼鏡で敵の挙動を読み解く、知性派の戦士。",
    quirk: "眼鏡",
    signatureOutfit: "丸眼鏡 + 革鎧 + 革表紙の戦術手帳",
    signatureBio: "本屋育ち。剣士には向かないと家族に言われ続けたが、敵の癖を眼鏡越しに観察するだけで一歩先を読めると気づいた。戦術手帳には倒した敵の癖が 87 ページ分書き連ねてあるという。",
    baseStats: { hp: 56, mp: 16, atk: 12, def: 8, mat: 4, mdf: 6, spd: 8 },
    uniqueSkills: [
      // 1. 基本攻撃 — 毎ターン使える主力。命中重視で堅実。
      {
        name: "観察打ち",
        description: "眼鏡越しに敵の動きを見据えてから一撃。命中率が高く、外しにくい基本攻撃。",
        type: "attack",
        element: null,
        power: 12,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 職業の代名詞、ボス級にも通る攻撃。
      {
        name: "眼鏡メテオ",
        description: "レンズで太陽光を一点に集め、敵全体に小さな隕石を降らせる。眼鏡戦士の代名詞。",
        type: "attack",
        element: "light",
        power: 24,
        cost: 14,
        cooldown: 4,
        targetType: "all_enemies",
      },
      // 3. 自バフ — 単発火力を伸ばす設計、必殺技と組み合わせる。
      {
        name: "分析の構え",
        description: "戦術手帳を開き敵の癖を読み解く。次の通常攻撃のクリティカル率 +50%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — Phase 1 サンプルで「観察眼」だったもの。役割は弱点公開で同じ。
      {
        name: "観察眼",
        description: "敵を 1 ターン凝視し、弱点属性とおおよその HP を味方に共有する。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "enemy",
      },
      // 5. 仲間援護 — heal 枠だが「医者ではなく観察者の応急手当」として職業性を保つ。
      {
        name: "冷徹な見立て",
        description: "仲間の傷を観察し、最も効率の良い応急手当を施す。HP を中量回復。",
        type: "heal",
        element: null,
        power: 18,
        cost: 8,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 全敵に効果、命中低下で次ターンの被ダメージも下げる。
      {
        name: "閃光乱反射",
        description: "眼鏡を瞬時にひらめかせ、全敵を眩ませる。光属性ダメージ + 1 ターン命中 -30%。",
        type: "attack",
        element: "light",
        power: 14,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — パッシブ風、戦闘の継戦能力を上げる。
      {
        name: "観察の習慣",
        description: "戦闘中も周囲を観察し続ける構え。3 ターン回避率 +20%、被ダメージ -10%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — C30 chain combo と相性◎、味方が先に動く設計でパーティ向き。
      {
        name: "予測射撃",
        description: "直前の味方スキルから敵の次手を読む。直前と異なる skill type なら威力 +30%。",
        type: "attack",
        element: null,
        power: 16,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — boss 戦の決め手、超大ダメージだが MP 大量消費・長 CD。
      {
        name: "終局視",
        description: "敵の運命を眼鏡越しに見切り、絶対的な弱点を一撃で突く。超大ダメージ、MP 大量消費。",
        type: "attack",
        element: "dark",
        power: 50,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature 反射 — 職業の象徴、ボス AOE に対する切り札。
      // NOTE: type="buff" で engine 上は self-buff 扱い。実際のダメージ反射ロジックは
      // battle.ts:resolveTurn に reflect 処理を追加する必要があり、本サイクルでは未実装。
      // BACKLOG に「眼鏡反射 reflect 実装」を登録予定。
      {
        name: "眼鏡反射",
        description: "1 ターン、受けた物理ダメージの 50% を相手に反射する眼鏡戦士の象徴 (反射ロジックは将来実装)。",
        type: "buff",
        element: "light",
        power: 0,
        cost: 12,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "巨漢戦士",
    category: "warrior",
    rank: "advanced",
    description: "見た目通りの怪力で大地ごと敵を揺らす。",
    quirk: "巨漢",
    signatureOutfit: "鋲付き胸当て + 巨大両手槌 + 山羊皮のマント",
    signatureBio: "北方の鉱山育ち。子供の頃に落盤事故で岩を素手で押し退けたという伝説があるが、本人たちは『たまたまだ』と笑う。怒鳴り声で動物が逃げる程度には怖い。",
    baseStats: { hp: 80, mp: 18, atk: 16, def: 12, mat: 2, mdf: 4, spd: 4 },
    uniqueSkills: [
      // 1. 基本攻撃 — 両手槌の素直な振り下ろし。
      {
        name: "岩砕き",
        description: "両手槌で大きく振り下ろす。素直だが重い、巨漢の基本攻撃。",
        type: "attack",
        element: null,
        power: 13,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 単体への大ダメージ。
      {
        name: "山割り",
        description: "両手槌を頭上から叩きつける必殺の一撃。岩盤すら砕く威力で敵を地に縫いつける。",
        type: "attack",
        element: "earth",
        power: 24,
        cost: 14,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 怒鳴り声で士気を引き上げ次撃強化。
      {
        name: "怒声",
        description: "腹の底から咆える。次の通常攻撃の威力 +50%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 威圧で攻撃意欲を削ぐ。
      {
        name: "威圧",
        description: "睨みつけて敵 1 体の戦意を削ぐ。atk -25% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 巨体を盾に庇う。
      {
        name: "庇い壁",
        description: "巨体を盾代わりにして味方 1 体を庇う。1 ターン受けるダメージを肩代わり。",
        type: "buff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 既存「地響き」(C31 既存スキル維持)。
      {
        name: "地響き",
        description: "地面を踏み砕き、敵全体に物理ダメージとスタン付与（30%）。",
        type: "attack",
        element: "earth",
        power: 14,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 構え長期。
      {
        name: "不動の構え",
        description: "両足を地に据えて 4 ターン def +30%、回避不可。仁王立ちの巨漢を誰も動かせない。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 直前 type と異なる連撃で +bonus。
      {
        name: "山崩し",
        description: "前段の構えを崩しに転じる連撃。直前と異なる type の後で威力上昇。",
        type: "attack",
        element: "earth",
        power: 16,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 全敵への超威力。
      {
        name: "山岳震",
        description: "両手槌を地に叩きつけ山ごと震わす。敵全体に超大物理ダメージ。",
        type: "attack",
        element: "earth",
        power: 45,
        cost: 28,
        cooldown: 8,
        targetType: "all_enemies",
      },
      // 10. signature — 巨漢の代名詞、本気の咆哮。
      {
        name: "怪力披露",
        description: "本気の咆哮で全身の力を引き出す。次の通常攻撃が確定で 2 段ヒット。巨漢戦士の代名詞。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "隻腕戦士",
    category: "warrior",
    rank: "advanced",
    description: "片腕を失っても剣を捨てない、執念の戦士。",
    quirk: "隻腕",
    signatureOutfit: "鋼の義手 + 重ね革鎧 + 革紐の片肩当て",
    signatureBio: "戦場で右腕を失った後、左腕一本で剣を振るう道を選んだ者たち。義手の重みで体幹を鍛え、片腕でしか出せない斜め斬り上げを編み出した。挫折は剣士を磨く。",
    baseStats: { hp: 70, mp: 18, atk: 15, def: 11, mat: 3, mdf: 5, spd: 6 },
    uniqueSkills: [
      // 1. 基本攻撃 — 片刃で軽く斬る、命中重視。
      {
        name: "片刃斬り",
        description: "義手の重みを支えに、左腕一本で素早く斬る。隻腕戦士の基本攻撃。",
        type: "attack",
        element: null,
        power: 12,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 義手の重みを乗せた渾身の斬り上げ。
      {
        name: "義手震斬",
        description: "義手の重みを利用した斜め斬り上げ。片腕でしか出せない軌道で敵を割る。",
        type: "attack",
        element: null,
        power: 23,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 既存「片刃の覚悟」(C31 既存スキル維持)。
      {
        name: "片刃の覚悟",
        description: "次の通常攻撃が必中 + クリティカル率 +30%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "self",
      },
      // 4. 敵デバフ — 鋼の義手で威圧、敵 atk 低下。
      {
        name: "義手の威圧",
        description: "鋼の義手を見せつけて敵 1 体を萎縮させる。atk -20% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 片腕でも仲間を守る。
      {
        name: "片腕の盾",
        description: "義手で味方 1 体を庇いつつ、def +25% 2 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 義手で広く薙ぎ払う。
      {
        name: "義手薙ぎ",
        description: "鋼の義手を大きく振り、敵全体に物理ダメージ。重い一撃が広く届く。",
        type: "attack",
        element: null,
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 執念で攻撃継続。
      {
        name: "執念",
        description: "失った片腕の代わりに研いだ意志。5 ターン atk +15%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 残心の構えから次の連撃。
      {
        name: "残心",
        description: "前段の動きを見極めての連撃。直前と異なる type の後で威力上昇。",
        type: "attack",
        element: null,
        power: 16,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 究極の片腕一撃。
      {
        name: "片刃奥義: 終斬",
        description: "片腕で振るえる最後の一撃。命を削って放つ斬撃で敵を真っ二つにする。",
        type: "attack",
        element: null,
        power: 50,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 義手を犠牲に次撃を 3 倍化。
      {
        name: "義手の代償",
        description: "義手の機構をひとつ犠牲にして力を引き出す。次の通常攻撃の威力 +200%。隻腕戦士の代名詞。",
        type: "buff",
        element: null,
        power: 0,
        cost: 14,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "双子戦士",
    category: "warrior",
    rank: "intermediate",
    description: "息の合った双子の連携で敵を翻弄する。",
    quirk: "双子",
    signatureOutfit: "色違いの鏡像鎧 + 細身の双剣 + 双子結び目の腕章",
    signatureBio: "幼少から二人で一人として育った者たち。互いの呼吸を読み、片方が攻める間にもう片方が守る。一人になっても、もう一人の影を背負って戦う。",
    baseStats: { hp: 60, mp: 18, atk: 13, def: 9, mat: 4, mdf: 6, spd: 9 },
    uniqueSkills: [
      // 1. 基本攻撃 — 双剣を交互に。
      {
        name: "双剣の呼吸",
        description: "双剣を交互に振るう、二人で一人の呼吸の基本攻撃。",
        type: "attack",
        element: null,
        power: 11,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 連続 3 段。
      {
        name: "双剣斬撃乱舞",
        description: "もう一人の影と並んで斬る。3 段連続の細かい斬撃。",
        type: "attack",
        element: null,
        power: 22,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 影の片割れと並ぶ短期バフ。
      {
        name: "影の片割れ",
        description: "もう一人の影と並ぶ。1 ターン回避率 +30%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 挟撃の構え。
      {
        name: "挟撃宣言",
        description: "敵 1 体を挟む構え。そちらの def -20% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — もう一人の影で守る。
      {
        name: "護りの片影",
        description: "影が味方 1 体に寄り添い、HP を中回復しつつ次の被弾を半減。",
        type: "heal",
        element: null,
        power: 16,
        cost: 10,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 双剣で全敵を薙ぐ。
      {
        name: "双剣の渦",
        description: "二人で囲むように敵全体を薙ぐ。風属性の連続斬撃。",
        type: "attack",
        element: "wind",
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 二人で一人として動き続ける。
      {
        name: "二人で一人",
        description: "もう一人の影が常に並ぶ。4 ターン spd +20% atk +10%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 連舞でチェーン強化。
      {
        name: "連舞",
        description: "片方が崩した敵にもう一人が斬り込む。直前と異なる type の後で威力上昇。",
        type: "attack",
        element: null,
        power: 15,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 鏡映双剣の連続 5 段。
      {
        name: "鏡映双剣奥義",
        description: "二人がかりの究極連撃。鏡像の軌跡で敵を 5 段連斬する。",
        type: "attack",
        element: null,
        power: 48,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 既存「鏡像連携」(C31 既存スキル維持)。
      {
        name: "鏡像連携",
        description: "次の 2 ターン、通常攻撃が確定で 2 段ヒットする。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "self",
      },
    ],
  },
  {
    name: "元踊り子戦士",
    category: "warrior",
    rank: "intermediate",
    description: "踊りの動作を剣の運びに転じた、舞型の剣士。",
    quirk: "元踊り子",
    signatureOutfit: "薄絹のスカーフ + 軽量胸当て + 踊り用の細刃刀",
    signatureBio: "舞踊団で生まれ育ち、ある日剣を握るように転じた者たち。流麗な歩法と回転を活かし、敵の側面を素早く取る。剣の軌跡が踊りの軌道と重なる。",
    baseStats: { hp: 50, mp: 18, atk: 12, def: 7, mat: 4, mdf: 5, spd: 12 },
    uniqueSkills: [
      // 1. 基本攻撃 — 舞いの歩法から繰り出す軽い斬。
      {
        name: "舞剣の歩",
        description: "踊りの歩法から流れるように繰り出す細刃の斬撃。軽快な基本攻撃。",
        type: "attack",
        element: null,
        power: 11,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 単体への決め舞。
      {
        name: "終舞: 一閃",
        description: "舞踏の終幕。回転の頂点で繰り出す細刃の渾身の一閃。",
        type: "attack",
        element: "wind",
        power: 23,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 舞踏の構え。
      {
        name: "舞踏の構え",
        description: "つま先で立ち踊り出す前の構え。1 ターン spd +30% 回避率 +20%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 煙霧の所作で命中低下。
      {
        name: "煙霧の所作",
        description: "薄絹を翻して敵の視界を惑わす。敵 1 体の命中率 -25% 2 ターン。",
        type: "debuff",
        element: "wind",
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 歓声の舞で士気回復。
      {
        name: "歓声の舞",
        description: "観客を魅了する舞で味方の傷を癒す。HP 中回復 + 状態異常 1 種解除。",
        type: "heal",
        element: null,
        power: 18,
        cost: 11,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 既存「舞剣の旋」(C31 既存スキル維持)。
      {
        name: "舞剣の旋",
        description: "敵全体に風属性ダメージ。自身の回避率 +15% 1 ターン。",
        type: "attack",
        element: "wind",
        power: 12,
        cost: 10,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 永遠の舞。
      {
        name: "永遠の舞",
        description: "踊り続ける限り傷つかない。4 ターン回避率 +25%。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 舞踏の連続技。
      {
        name: "舞踏連舞",
        description: "前段の動きを引き継いで連続斬。直前と異なる type の後で威力上昇。",
        type: "attack",
        element: "wind",
        power: 15,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 最終楽章。
      {
        name: "最終楽章",
        description: "舞踏の終幕に放つ究極の連続斬。一気に 7 段、敵全体を巻き込む。",
        type: "attack",
        element: "wind",
        power: 46,
        cost: 28,
        cooldown: 8,
        targetType: "all_enemies",
      },
      // 10. signature — 優雅な絶舞、踊り子戦士の代名詞。
      {
        name: "優雅なる絶舞",
        description: "1 ターン全ての攻撃が必中 + 与ダメージ +30%。元踊り子戦士の代名詞。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 14,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "元医者戦士",
    category: "warrior",
    rank: "intermediate",
    description: "人の体を熟知した、急所狙いの戦士。",
    quirk: "元医者",
    signatureOutfit: "白衣の上に革鎧 + 解剖図の彫られた小剣 + 包帯の腰巻",
    signatureBio: "戦場で多くの命を看取り、剣を取って戦う側に転じた者たち。骨格と筋繊維の知識から急所を読み、最小の動作で最大の傷を与える。",
    baseStats: { hp: 56, mp: 18, atk: 13, def: 8, mat: 5, mdf: 6, spd: 8 },
    uniqueSkills: [
      // 1. 基本攻撃 — 解剖知識を活かした的確な斬り。
      {
        name: "解剖斬",
        description: "骨格と筋繊維の知識から急所を読み斬る。命中率の高い基本攻撃。",
        type: "attack",
        element: null,
        power: 12,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 致命傷を読む。
      {
        name: "致命傷を読む",
        description: "解剖図に重ねる視線で致命点を見抜く。クリティカル率 +50% の渾身一撃。",
        type: "attack",
        element: null,
        power: 23,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 医学の構え。
      {
        name: "医学の構え",
        description: "解剖図を脳裏に開く。次の通常攻撃のクリティカル率 +40%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 弱点公開。
      {
        name: "弱点公開",
        description: "敵 1 体の体の構造を読み、def -25% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 応急手当。
      {
        name: "応急手当",
        description: "包帯と医学知識で味方を素早く治療。HP 中回復 + 出血 / 火傷を解除。",
        type: "heal",
        element: null,
        power: 20,
        cost: 11,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 血流断ち。
      {
        name: "血流断ち",
        description: "解剖知識を活かした広範囲斬。敵全体に物理ダメージ + 出血 (40%)。",
        type: "attack",
        element: null,
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 冷静な観察。
      {
        name: "冷静な観察",
        description: "戦場の流れを冷静に診る。4 ターン全攻撃のクリ率 +20%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 既存「急所突き」(C31 既存スキル維持)。
      {
        name: "急所突き",
        description: "敵 1 体に物理ダメージ。クリティカル時に【出血】付与。",
        type: "attack",
        element: null,
        power: 14,
        cost: 8,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 外科剣奥義。
      {
        name: "外科剣奥義",
        description: "解剖図を全て胸に刻んで放つ究極の斬撃。敵の最も致命的な箇所を貫く。",
        type: "attack",
        element: null,
        power: 50,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 死期を診る。
      {
        name: "死期を診る",
        description: "敵 1 体の死期を診断する。HP 50% 以下の敵に追加 100% ダメージ。元医者戦士の代名詞。",
        type: "attack",
        element: "dark",
        power: 18,
        cost: 13,
        cooldown: 5,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元囚人戦士",
    category: "warrior",
    rank: "advanced",
    description: "牢獄で死を覚悟した日々を経た、捨て身の戦士。",
    quirk: "元囚人",
    signatureOutfit: "破れた囚人服 + 鎖が残った手枷 + 即席の鈍刀",
    signatureBio: "理不尽な罪で投獄され、運命の隙間で逃げ出した者たち。獄中で鍛えた捨て身の戦い方は常識外れ。鎖を武器にも使う。",
    baseStats: { hp: 78, mp: 18, atk: 15, def: 10, mat: 2, mdf: 4, spd: 6 },
    uniqueSkills: [
      // 1. 基本攻撃 — 手枷で殴る。
      {
        name: "手枷叩き",
        description: "鎖の付いた手枷を振り上げて殴り倒す。即興の暴力、囚人戦士の基本攻撃。",
        type: "attack",
        element: null,
        power: 13,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 逆境の囚人剣。
      {
        name: "囚人剣斬",
        description: "獄中で鍛えた捨て身の渾身斬り。HP が低いほど威力が増す。",
        type: "attack",
        element: null,
        power: 24,
        cost: 14,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 捨て身の覚悟。
      {
        name: "捨て身の覚悟",
        description: "命を惜しまず構える。次の通常攻撃の威力 +60%、被弾 +20%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 鎖で縛る。
      {
        name: "鎖縛り",
        description: "手枷の鎖で敵 1 体を縛る。spd -30% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 共犯者を救う。
      {
        name: "共犯者を救う",
        description: "獄中の絆を呼び起こし味方 1 体の HP を回復 + 拘束系 debuff を解除。",
        type: "heal",
        element: null,
        power: 18,
        cost: 11,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 鉄格子薙ぎ。
      {
        name: "鉄格子薙ぎ",
        description: "鈍刀と手枷の鎖を振り回し、敵全体に物理ダメージ。",
        type: "attack",
        element: null,
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 不退転。
      {
        name: "不退転",
        description: "もう失うものがない。5 ターン atk +20%、自身に対するクリ無効化。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 既存「鎖鳴り」(C31 既存スキル維持)。
      {
        name: "鎖鳴り",
        description: "敵 1 体に物理ダメージ + スタン付与（50%）。",
        type: "attack",
        element: null,
        power: 13,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
      // 9. 究極 — 破獄一閃。
      {
        name: "破獄一閃",
        description: "牢獄を破った日の記憶を込めた一閃。鎖ごと敵を断ち切る。",
        type: "attack",
        element: null,
        power: 50,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 死刑囚の最後。
      {
        name: "死刑囚の最後",
        description: "HP 30% 以下の時のみ発動可能。次の攻撃の威力 +250%。元囚人戦士の代名詞。",
        type: "buff",
        element: "dark",
        power: 0,
        cost: 13,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "雪国戦士",
    category: "warrior",
    rank: "intermediate",
    description: "極寒の地で生まれ育った、寒さに動じない戦士。",
    quirk: "雪国育ち",
    signatureOutfit: "白熊の毛皮マント + 氷柄の長剣 + 銀のブローチ",
    signatureBio: "雪深い北の集落で育ち、零下の朝を平気で歩く者たち。寒さを敵にする魔法に強い耐性を持ち、剣に氷を纏わせる古い技を伝えている。",
    baseStats: { hp: 64, mp: 18, atk: 13, def: 10, mat: 4, mdf: 8, spd: 6 },
    uniqueSkills: [
      // 1. 基本攻撃 — 氷柄の長剣で素直に斬る。
      {
        name: "氷柄斬",
        description: "氷柄の長剣で冷気を伝わせて斬る。雪国戦士の基本攻撃。",
        type: "attack",
        element: "water",
        power: 12,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 氷雪の渾身斬。
      {
        name: "氷雪渾斬",
        description: "氷柄の長剣に呼吸ごと冷気を纏わせる必殺の一撃。霜が傷口を凍らせる。",
        type: "attack",
        element: "water",
        power: 24,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 冷気纏。
      {
        name: "冷気纏",
        description: "全身に薄い霜を纏う。次の通常攻撃に水属性 + spd 低下効果が乗る。",
        type: "buff",
        element: "water",
        power: 0,
        cost: 7,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 霜結び。
      {
        name: "霜結び",
        description: "敵 1 体の関節を凍らせる。spd -25%・atk -15% 2 ターン。",
        type: "debuff",
        element: "water",
        power: 0,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 雪見舞。
      {
        name: "雪見舞",
        description: "雪解け水を傷口に当てて治療。味方 1 体の HP 中回復 + 火傷を解除。",
        type: "heal",
        element: "water",
        power: 18,
        cost: 11,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 氷霧吹雪。
      {
        name: "氷霧吹雪",
        description: "剣を振り抜いて吹雪を起こす。敵全体に水属性ダメージ + spd 低下。",
        type: "attack",
        element: "water",
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 雪国の血。
      {
        name: "雪国の血",
        description: "寒さに動じない雪国の血が冷気を魔力に変える。4 ターン水属性ダメージ +30%。",
        type: "buff",
        element: "water",
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 既存「凍刃の一撃」(C31 既存スキル維持)。
      {
        name: "凍刃の一撃",
        description: "敵 1 体に水属性ダメージ + spd 低下 1 ターン。",
        type: "attack",
        element: "water",
        power: 14,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 絶対零度斬。
      {
        name: "絶対零度斬",
        description: "氷柄の長剣に絶対零度を集める究極の斬撃。敵を芯まで凍結させ、命を断つ。",
        type: "attack",
        element: "water",
        power: 50,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 雪国の祈り。
      {
        name: "雪国の祈り",
        description: "雪深い故郷に祈り、3 ターン全攻撃に【凍結】30% 付与。雪国戦士の代名詞。",
        type: "buff",
        element: "water",
        power: 0,
        cost: 13,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "海賊崩れの戦士",
    category: "warrior",
    rank: "advanced",
    description: "船を捨て、陸で剣を振るう元海賊。",
    quirk: "海賊崩れ",
    signatureOutfit: "塩で擦り切れたバンダナ + 短刀と曲刀 + 金の耳輪",
    signatureBio: "船と仲間を一夜にして失い、陸に上がった者たち。海上で鍛えた足捌きと、不規則な揺れの中で身につけた間合いの取り方は陸の剣士には真似できない。",
    baseStats: { hp: 60, mp: 18, atk: 14, def: 8, mat: 3, mdf: 5, spd: 11 },
    uniqueSkills: [
      // 1. 基本攻撃 — 短刀と曲刀の素直な二刀斬り。
      {
        name: "短刀曲刀斬",
        description: "短刀で受けて曲刀で斬る、海賊上がりの素直な二刀基本攻撃。",
        type: "attack",
        element: null,
        power: 12,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 船底斬り。
      {
        name: "船底斬り",
        description: "敵の足元から斬り上げる必殺の一撃。船底を割る要領で重心ごと崩す。",
        type: "attack",
        element: null,
        power: 23,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
      // 3. 自バフ — 揺れる足捌き。
      {
        name: "揺れる足捌き",
        description: "波間の不規則な揺れを思い出して立つ。1 ターン回避率 +25%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 6,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 海風の所作。
      {
        name: "海風の所作",
        description: "塩混じりの風を顔に吹きつけるような所作。敵 1 体の命中率 -20% 2 ターン。",
        type: "debuff",
        element: "wind",
        power: 0,
        cost: 7,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 酒場流の応急処置。
      {
        name: "酒場流の応急処置",
        description: "酒で消毒・布で縛るという海賊流の手当。味方 1 体の HP 回復 + 出血解除。",
        type: "heal",
        element: null,
        power: 16,
        cost: 10,
        cooldown: 3,
        targetType: "ally",
      },
      // 6. AOE — 曲刀の渦。
      {
        name: "曲刀の渦",
        description: "曲刀を振り回して周囲全体を斬る。船上で覚えた回転斬り。",
        type: "attack",
        element: null,
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 波間の戦士。
      {
        name: "波間の戦士",
        description: "船上の不規則な揺れの感覚で 4 ターン回避率 +20%・spd +10%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 既存「船揺れ斬り」(C31 既存スキル維持)。
      {
        name: "船揺れ斬り",
        description: "敵 1 体に物理ダメージ + 自身の回避率 +20% 1 ターン。",
        type: "attack",
        element: null,
        power: 13,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
      // 9. 究極 — 海賊の最後。
      {
        name: "海賊の最後",
        description: "失った船と仲間の記憶を込めた究極の連続斬。短刀と曲刀の連舞で敵を裂く。",
        type: "attack",
        element: null,
        power: 48,
        cost: 28,
        cooldown: 8,
        targetType: "enemy",
      },
      // 10. signature — 海風の挑発。
      {
        name: "海風の挑発",
        description: "口笛混じりの挑発で敵全体の注意を自身に集中。3 ターン被弾率 +30%、回避率 +30%。海賊崩れの代名詞。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 14,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "元騎士団長",
    category: "warrior",
    rank: "legendary",
    description: "栄光と挫折の両方を知る、老練の指揮官。",
    quirk: "元騎士団長",
    signatureOutfit: "白銀の儀礼鎧 + 紋章入りの大剣 + 紅のマント",
    signatureBio: "千の兵を率い、千の戦場で勝敗を分けた者たち。称号は遠い記憶でも、戦場での目の配りと味方への号令は今も衰えない。",
    baseStats: { hp: 75, mp: 22, atk: 16, def: 12, mat: 4, mdf: 8, spd: 6 },
    uniqueSkills: [
      // 1. 基本攻撃 — 紋章入りの大剣による礼節ある一撃。
      {
        name: "儀礼剣斬",
        description: "紋章入りの大剣による真っ直ぐで美しい一撃。元指揮官の基本攻撃。",
        type: "attack",
        element: null,
        power: 13,
        cost: 2,
        cooldown: 0,
        targetType: "enemy",
      },
      // 2. 必殺技 — 既存「総攻撃の号令」を全体 buff の必殺技として位置付け。
      {
        name: "総攻撃の号令",
        description: "味方全員の atk +20% 2 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 16,
        cooldown: 5,
        targetType: "all_allies",
      },
      // 3. 自バフ — 指揮官の構え。
      {
        name: "指揮官の構え",
        description: "千戦の経験を呼び戻して立つ。次の通常攻撃のクリ率 +40% + 命中 +20%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 2,
        targetType: "self",
      },
      // 4. 敵デバフ — 指揮官の威圧。
      {
        name: "指揮官の威圧",
        description: "鋭い視線で敵 1 体を萎縮させる。atk -25% 2 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
      // 5. 仲間援護 — 号令: 治療。
      {
        name: "号令: 治療",
        description: "短く鋭い号令で味方全員の HP を中回復。指揮官の声は治癒の力を持つ。",
        type: "heal",
        element: null,
        power: 16,
        cost: 13,
        cooldown: 3,
        targetType: "all_allies",
      },
      // 6. AOE — 軍剣の薙ぎ。
      {
        name: "軍剣の薙ぎ",
        description: "紋章入りの大剣で敵全体を薙ぎ払う。長年の指揮で磨いた間合い取り。",
        type: "attack",
        element: null,
        power: 14,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
      // 7. 持続バフ — 百戦の心得。
      {
        name: "百戦の心得",
        description: "千戦の経験で戦場全体を読む。4 ターン自身の atk +15%・def +15%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 5,
        targetType: "self",
      },
      // 8. 連携 — 突撃連携。
      {
        name: "突撃連携",
        description: "前段の動きを引き継いで突撃。直前と異なる type の後で威力上昇。",
        type: "attack",
        element: null,
        power: 16,
        cost: 9,
        cooldown: 2,
        targetType: "enemy",
      },
      // 9. 究極 — 最終号令。
      {
        name: "最終号令",
        description: "指揮官として最後の号令。味方全員の attack 即座実行 + 敵全体に物理ダメージ。",
        type: "attack",
        element: null,
        power: 50,
        cost: 30,
        cooldown: 8,
        targetType: "all_enemies",
      },
      // 10. signature — 紋章の覚醒。
      {
        name: "紋章の覚醒",
        description: "紅マントが輝き、味方全員の atk + def + spd を 3 ターン +20%。元騎士団長の代名詞。",
        type: "buff",
        element: "light",
        power: 0,
        cost: 15,
        cooldown: 5,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "退役老兵",
    category: "warrior",
    rank: "advanced",
    description: "百戦を生き延びた、戦場の生き字引。",
    quirk: "退役老兵",
    signatureOutfit: "傷だらけの兜 + 銀の鎖帷子 + 古い軍剣",
    signatureBio: "若き戦士が皆死ぬ戦場を、何故か生き残り続けた者たち。死なないコツを知っているのか、死神に呆れられただけなのかは本人にも分からない。",
    baseStats: { hp: 68, mp: 12, atk: 14, def: 12, mat: 3, mdf: 6, spd: 5 },
    uniqueSkills: [
      {
        name: "退き際の一撃",
        description: "自身の HP が 30% 以下なら威力 1.5 倍の物理攻撃。",
        type: "attack",
        element: null,
        power: 18,
        cost: 10,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元獣狩り戦士",
    category: "warrior",
    rank: "intermediate",
    description: "野獣との一対一を生き抜いた、獣の心を読む戦士。",
    quirk: "元獣狩り",
    signatureOutfit: "毛皮の肩当て + 骨で柄を作った狩剣 + 罠用ロープ",
    signatureBio: "山中で巨大な獣を狩り続けた者たち。獣の呼吸を読む経験は、対人戦闘にも活きる。獣系の敵への直感的な対処に長ける。",
    baseStats: { hp: 60, mp: 10, atk: 14, def: 9, mat: 3, mdf: 5, spd: 9 },
    uniqueSkills: [
      {
        name: "獣狩りの一閃",
        description: "獣系の敵に大ダメージ。それ以外は半減。",
        type: "attack",
        element: null,
        power: 22,
        cost: 11,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元密漁者戦士",
    category: "warrior",
    rank: "intermediate",
    description: "禁猟区で生計を立てた、影の刈り手。",
    quirk: "元密漁者",
    signatureOutfit: "革のフード + 投網と短刀 + 防水ブーツ",
    signatureBio: "夜の禁漁区を渡り歩いた者たち。森や水辺の音を読む耳を持ち、誰も気付かない位置から仕掛ける。違法だった日々の経験が今は剣の腕に化けた。",
    baseStats: { hp: 56, mp: 12, atk: 13, def: 8, mat: 4, mdf: 6, spd: 10 },
    uniqueSkills: [
      {
        name: "投網の妨害",
        description: "敵 1 体の spd を 2 ターン -30%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },

  // ---------- MAGE ----------
  {
    name: "猫好き魔導師",
    category: "mage",
    rank: "intermediate",
    description: "塔に住み着いた野良猫たちと対話する、変わり者の魔導師。",
    quirk: "猫好き",
    signatureOutfit: "三毛猫の毛皮ローブ + 木の杖 + 革紐に通した小さな鈴",
    signatureBio: "塔学生だった頃に生贄の儀式に使われそうになった子猫を救い、退学処分を受けた者たち。今は野良猫と暮らし、彼らの夢を読む独自の魔法を編み出した。誰も信じないが、効く。",
    baseStats: { hp: 38, mp: 30, atk: 4, def: 4, mat: 16, mdf: 10, spd: 7 },
    uniqueSkills: [
      {
        name: "招き猫の歌",
        description: "味方全員の運（luk）を 1 ターン上昇させ、ドロップ判定が改善する。",
        type: "buff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "不眠魔導師",
    category: "mage",
    rank: "advanced",
    description: "三日三晩眠らずに研究する病的な探究者。",
    quirk: "不眠",
    signatureOutfit: "目の下のクマ + 黒外套 + 開きっぱなしの夢日記",
    signatureBio: "10 年眠っていないと言われる者たち。『眠ると夢に喰われる』と語る一方で、夢の側からも入れる魔法を発明した。眠る敵の意識に侵入し、悪夢で削る。",
    baseStats: { hp: 32, mp: 36, atk: 3, def: 3, mat: 18, mdf: 8, spd: 9 },
    uniqueSkills: [
      {
        name: "夢渡り",
        description: "敵に【沈黙】+【出血】を同時付与(必中)。",
        type: "debuff",
        element: "dark",
        power: 8,
        cost: 14,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "喘息魔導師",
    category: "mage",
    rank: "intermediate",
    description: "息を整えるたびに詠唱を区切る、独自詠唱派。",
    quirk: "喘息",
    signatureOutfit: "薄手の絹外套 + 短い杖 + 喉に巻いた青い布",
    signatureBio: "幼い頃から呼吸器が弱く、長い詠唱が続けられない者たち。短く切れた呪文を高速で重ねる独自の流派を編み出した。皮肉にも、その節回しは詠唱の常識を上書きした。",
    baseStats: { hp: 34, mp: 32, atk: 3, def: 4, mat: 17, mdf: 10, spd: 9 },
    uniqueSkills: [
      {
        name: "断章詠唱",
        description: "敵 1 体に火属性ダメージ + 次ターン同種攻撃の cost を半減。",
        type: "attack",
        element: "fire",
        power: 14,
        cost: 8,
        cooldown: 2,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "妖精と契約した魔導師",
    category: "mage",
    rank: "advanced",
    description: "妖精と等価交換の契約を交わした、奇妙な魔導師。",
    quirk: "妖精と契約",
    signatureOutfit: "蛍光する紋様の杖 + 緑のローブ + 肩に止まる発光体",
    signatureBio: "幼少に妖精と『片目で世界の真実を見る』代償の契約を交わした者たち。妖精は契約者のそばを離れず、戦闘中にも光で攻撃を補助する。",
    baseStats: { hp: 38, mp: 36, atk: 3, def: 4, mat: 18, mdf: 11, spd: 8 },
    uniqueSkills: [
      {
        name: "妖精の閃光",
        description: "敵全体に光属性ダメージ。暗黒系の敵には 1.5 倍。",
        type: "attack",
        element: "light",
        power: 14,
        cost: 13,
        cooldown: 3,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "元教師魔導師",
    category: "mage",
    rank: "intermediate",
    description: "村の塾で長く教えた、説明上手の魔導師。",
    quirk: "元教師",
    signatureOutfit: "チョーク粉が残る外套 + 木製の指示棒 + 銀縁の眼鏡",
    signatureBio: "村の子供たちに字と算術を教えていた者たち。教えるうちに自分でも書を読み込み、独学で魔導の道に入った。詠唱には黒板に書いた式を読み上げる癖がある。",
    baseStats: { hp: 36, mp: 30, atk: 3, def: 4, mat: 16, mdf: 10, spd: 8 },
    uniqueSkills: [
      {
        name: "解説詠唱",
        description: "味方全員の mat +15% 2 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "数学狂魔導師",
    category: "mage",
    rank: "advanced",
    description: "魔法を数式で記述する、純粋数学派。",
    quirk: "数学狂",
    signatureOutfit: "数式が刺繍された外套 + 計算尺の付いた杖 + 黒インクの指",
    signatureBio: "魔法を直感ではなく数式で扱う流派の者たち。式が美しいほど効果が高いと信じ、戦闘中も最適化を続ける。常人には呟きが聞き取れない。",
    baseStats: { hp: 36, mp: 38, atk: 3, def: 4, mat: 19, mdf: 9, spd: 9 },
    uniqueSkills: [
      {
        name: "微分の刃",
        description: "敵 1 体に魔法ダメージ + def を 1 ターン -25%。",
        type: "attack",
        element: null,
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "不器用魔導師",
    category: "mage",
    rank: "intermediate",
    description: "詠唱を時々間違えるが、間違いごと爆発する魔導師。",
    quirk: "不器用",
    signatureOutfit: "煤けた帽子 + ヒビが入った杖 + 焦げ跡の残るローブ",
    signatureBio: "詠唱の途中で言い間違える癖が抜けない者たち。普通なら不発のところ、なぜか別の魔法に化けて発動する。本人も結果を予測できない。",
    baseStats: { hp: 38, mp: 32, atk: 3, def: 4, mat: 17, mdf: 9, spd: 7 },
    uniqueSkills: [
      {
        name: "不発詠唱",
        description: "ランダム属性(火/水/風/闇/光) で敵 1 体に魔法ダメージ。",
        type: "attack",
        element: null,
        power: 17,
        cost: 10,
        cooldown: 2,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "沈黙派魔導師",
    category: "mage",
    rank: "advanced",
    description: "言葉を一切発さずに魔法を編む、無音流派。",
    quirk: "沈黙派",
    signatureOutfit: "黒のフード + 木彫りの仮面 + 銀の符を巻いた杖",
    signatureBio: "幼少に声を失った者たち、もしくは自ら誓いとして話さない者たち。言葉に頼らない詠唱は察知が難しく、敵に気付かれずに発動できる。",
    baseStats: { hp: 36, mp: 34, atk: 3, def: 4, mat: 18, mdf: 11, spd: 8 },
    uniqueSkills: [
      {
        name: "無音呪文",
        description: "敵 1 体に必中の闇属性ダメージ +【沈黙】付与。",
        type: "debuff",
        element: "dark",
        power: 12,
        cost: 14,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "古文書狂魔導師",
    category: "mage",
    rank: "advanced",
    description: "失われた古代文字を読む、書庫の住人。",
    quirk: "古文書狂",
    signatureOutfit: "羊皮紙のロール束 + 銀の指輪 + 古代文字が縫い込まれたローブ",
    signatureBio: "失われた古代魔法の研究に生涯を費やす者たち。死語と呼ばれる詠唱を蘇らせ、現代魔法には無い効果を再現する。",
    baseStats: { hp: 34, mp: 36, atk: 3, def: 3, mat: 19, mdf: 10, spd: 7 },
    uniqueSkills: [
      {
        name: "古文の一節",
        description: "敵全体に闇属性ダメージ + 30% で【呪い化】付与。",
        type: "attack",
        element: "dark",
        power: 13,
        cost: 13,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "双頭魔導師",
    category: "mage",
    rank: "legendary",
    description: "二つの首が同時に詠唱する、異形の天才。",
    quirk: "双頭",
    signatureOutfit: "首が二本通る特注ローブ + 双子用の杖 + 金縁の眼鏡 4 枚",
    signatureBio: "生まれつき双頭の魔導師。二つの脳が同時に異なる詠唱を編む。意見が割れると詠唱が分裂し、相乗効果も内部矛盾も両方起きる。",
    baseStats: { hp: 38, mp: 38, atk: 3, def: 4, mat: 20, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "二重詠唱",
        description: "今ターン中にスキルを 2 回使用可能(次ターン MP 倍消費)。",
        type: "buff",
        element: null,
        power: 0,
        cost: 18,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "元錬金術師",
    category: "mage",
    rank: "intermediate",
    description: "鉱物と薬品を読む化学者あがりの魔導師。",
    quirk: "元錬金術師",
    signatureOutfit: "腰のフラスコホルダー + 薬品で焦げた手袋 + 黒のローブ",
    signatureBio: "元は錬金術師の徒弟だった者たち。物質変成の理を魔法に応用し、詠唱と薬品を組み合わせた独自の魔導を編み出した。",
    baseStats: { hp: 36, mp: 32, atk: 3, def: 4, mat: 17, mdf: 10, spd: 8 },
    uniqueSkills: [
      {
        name: "錬成の爆発",
        description: "敵 1 体に火属性ダメージ + 50% で【火傷】付与。",
        type: "attack",
        element: "fire",
        power: 16,
        cost: 11,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元天文学者",
    category: "mage",
    rank: "advanced",
    description: "星の運行を魔法に変換する、夜空の読み手。",
    quirk: "元天文学者",
    signatureOutfit: "星座図の刺繍されたローブ + 銀の懐中星座盤 + 三日月のブローチ",
    signatureBio: "塔の上で星を観測し続けた末に、魔導の道に転じた者たち。今日の星の配置で発動する魔法を選び、計算ミスで誤爆することもある。",
    baseStats: { hp: 36, mp: 36, atk: 3, def: 4, mat: 18, mdf: 11, spd: 9 },
    uniqueSkills: [
      {
        name: "星辰連環",
        description: "敵 1 体に光属性ダメージ + 自身の mat +10% 2 ターン。",
        type: "attack",
        element: "light",
        power: 15,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元戦場医魔導師",
    category: "mage",
    rank: "intermediate",
    description: "戦場で命を救った末に魔導に転じた、治療派の魔導師。",
    quirk: "元戦場医",
    signatureOutfit: "白い前掛け + 治癒紋の入った杖 + 血で汚れた包帯",
    signatureBio: "戦場で多くの兵を治療した経験から、魔法を治癒に活かす道を選んだ者たち。傷の早期判別と急所の補強を同時にこなす。",
    baseStats: { hp: 38, mp: 34, atk: 3, def: 4, mat: 17, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "戦場療法",
        description: "味方全員の HP を回復 + 状態異常 1 種を解除。",
        type: "heal",
        element: "light",
        power: 18,
        cost: 14,
        cooldown: 3,
        targetType: "all_allies",
      },
    ],
  },

  // ---------- ROGUE ----------
  {
    name: "甘党盗賊",
    category: "rogue",
    rank: "beginner",
    description: "甘いものに弱い、軽口の盗賊。",
    quirk: "甘党",
    signatureOutfit: "ピンクのフード + 飴の包み紙のポーチ + 短剣 2 本",
    signatureBio: "孤児院の脱走組。甘いケーキを盗むためだけに男爵邸に侵入し、ついでに金庫から銅貨も持ち帰る類の連中。仲間からは『砂糖が動力源』と呼ばれている。",
    baseStats: { hp: 36, mp: 14, atk: 11, def: 5, mat: 6, mdf: 5, spd: 14 },
    uniqueSkills: [
      {
        name: "甘い罠",
        description: "敵 1 体に物理ダメージ。次ターン敵が味方を狙う確率を 30% 下げる。",
        type: "debuff",
        element: null,
        power: 10,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "影語り",
    category: "rogue",
    rank: "advanced",
    description: "自分の影と会話できる暗殺者。",
    quirk: "影",
    signatureOutfit: "黒の半袖 + 黒の細刃 + 自分の影が分離した第二の輪郭",
    signatureBio: "幼い頃に呪術師に呪われ、影が独立して動くようになった者たち。本人より影の方が口数が多い。戦闘中、影が単独で攻撃を仕掛ける。",
    baseStats: { hp: 42, mp: 18, atk: 14, def: 6, mat: 8, mdf: 6, spd: 16 },
    uniqueSkills: [
      {
        name: "影分身",
        description: "次の通常攻撃が 2 回発動する（影が 1 回追加で攻撃）。",
        type: "buff",
        element: "dark",
        power: 0,
        cost: 10,
        cooldown: 4,
        targetType: "self",
      },
    ],
  },
  {
    name: "元道化師の盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "笑わせて懐に入る、元舞台人の盗賊。",
    quirk: "元道化師",
    signatureOutfit: "色違いの靴 + 鈴付きの帽子 + 投げナイフ 5 本",
    signatureBio: "祭りの広場で観衆を笑わせていた者たち。話術と急な転倒、即興の踊りで相手の気を逸らす。観客から銀貨を貰う側から、敵から命を奪う側に転じた。",
    baseStats: { hp: 38, mp: 16, atk: 11, def: 5, mat: 7, mdf: 6, spd: 15 },
    uniqueSkills: [
      {
        name: "笑わせの一撃",
        description: "敵 1 体に物理ダメージ + 50% で【混乱】(行動を 30% 失敗)。",
        type: "debuff",
        element: null,
        power: 11,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "美食家盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "高級料理のためなら命を懸ける、舌の鋭い盗賊。",
    quirk: "美食家",
    signatureOutfit: "シェフの帽子 + 銀のカトラリーセット + ワインボトルの腰下げ",
    signatureBio: "美食のためなら王宮にも忍び込む者たち。匂いと味で食材の産地を当てる鋭い感覚を持ち、敵が食べた料理から動きを推測する。",
    baseStats: { hp: 38, mp: 14, atk: 12, def: 6, mat: 6, mdf: 5, spd: 14 },
    uniqueSkills: [
      {
        name: "毒見の心得",
        description: "敵 1 体の状態異常を吸収して自身の atk +20% 1 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元医療助手の盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "急所と痛み止めを知る、影の医療派盗賊。",
    quirk: "元医療助手",
    signatureOutfit: "白い手袋 + 解剖刀 + 鎮痛草の小袋",
    signatureBio: "村医者の助手から、より良い報酬を求めて闇商売に流れた者たち。痛みを止める知識を逆用して急所を狙う。",
    baseStats: { hp: 36, mp: 18, atk: 12, def: 5, mat: 8, mdf: 6, spd: 15 },
    uniqueSkills: [
      {
        name: "麻痺の一突",
        description: "敵 1 体に物理ダメージ + 60% で【スタン】付与。",
        type: "attack",
        element: null,
        power: 12,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "港育ちの盗賊",
    category: "rogue",
    rank: "beginner",
    description: "港の路地裏で育った、塩風の若者。",
    quirk: "港育ち",
    signatureOutfit: "塩風で擦れた半袖 + 短刀 + 鈍く光る真鍮の指輪",
    signatureBio: "港の混雑の中で育ち、人波を縫って財布を抜く技を覚えた者たち。船員の方言を 5 つ操り、密航にも応じる。",
    baseStats: { hp: 36, mp: 14, atk: 11, def: 5, mat: 6, mdf: 5, spd: 16 },
    uniqueSkills: [
      {
        name: "群衆抜け",
        description: "1 ターン回避率 +50%、敵から狙われない。",
        type: "buff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "self",
      },
    ],
  },
  {
    name: "双子盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "息の合った双子の連携で財布を抜く。",
    quirk: "双子",
    signatureOutfit: "色違いの帯 + 細身の双短刀 + 双子結び目の腕章",
    signatureBio: "幼少から二人で一つの仕事を分担する者たち。片方が囮、もう片方が本命。一人になっても、もう一人の影がそばを歩く錯覚を覚える。",
    baseStats: { hp: 38, mp: 16, atk: 12, def: 5, mat: 7, mdf: 6, spd: 17 },
    uniqueSkills: [
      {
        name: "二段刺し",
        description: "敵 1 体に物理ダメージを 2 回。",
        type: "attack",
        element: null,
        power: 9,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "写真記憶の盗賊",
    category: "rogue",
    rank: "advanced",
    description: "見たものを忘れない、完璧記憶の偵察役。",
    quirk: "写真記憶",
    signatureOutfit: "黒の単眼鏡 + 紙束を巻いた帯 + 白手袋",
    signatureBio: "見たものを正確に思い出せる、まれな脳の持ち主たち。屋敷の間取り、衛兵のローテーション、貴族の癖を一度の視察で覚える。",
    baseStats: { hp: 38, mp: 18, atk: 11, def: 6, mat: 8, mdf: 6, spd: 15 },
    uniqueSkills: [
      {
        name: "弱点記録",
        description: "敵 1 体の弱点を 1 ターン公開し、味方全員の対象命中 +30%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "偽名常用の盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "本名を誰も知らない、十数の名を使い分ける盗賊。",
    quirk: "偽名常用",
    signatureOutfit: "替えのカツラ 3 種 + 偽の身分証 + 黒い手袋",
    signatureBio: "本名を捨てて十年、誰も本人を本名で呼ばない者たち。場面ごとに身分を切り替え、追っ手も誰を追っているか分からなくなる。",
    baseStats: { hp: 36, mp: 16, atk: 12, def: 5, mat: 7, mdf: 6, spd: 16 },
    uniqueSkills: [
      {
        name: "別人成り",
        description: "1 ターン敵のターゲットから外れる + 次の通常攻撃が必中。",
        type: "buff",
        element: null,
        power: 0,
        cost: 9,
        cooldown: 3,
        targetType: "self",
      },
    ],
  },
  {
    name: "動物使いの盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "犬や鳥に仕事を任せる、間接派の盗賊。",
    quirk: "動物使い",
    signatureOutfit: "鳥の餌入れ + 犬笛 + 動物の毛が付いたマント",
    signatureBio: "幼少から動物に懐かれる体質の者たち。鳩や犬、猫を使い分けて偵察し、屋敷の裏口を確認する。動物に頼り過ぎて、人間の判断は時々鈍る。",
    baseStats: { hp: 38, mp: 16, atk: 11, def: 6, mat: 7, mdf: 6, spd: 14 },
    uniqueSkills: [
      {
        name: "鳩偵察",
        description: "敵全体の弱点属性を 2 ターン公開 + 自身の spd +10% 2 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "元軍楽隊の盗賊",
    category: "rogue",
    rank: "intermediate",
    description: "軍楽隊で鍛えた音感で気配を読む。",
    quirk: "元軍楽隊",
    signatureOutfit: "古い軍服の上衣 + 折りたたみ式の鼓 + 短刀",
    signatureBio: "元は軍の楽隊員だった者たち。退役後に身を持ち崩したが、戦場で鍛えた敵の足音を読む耳は今も鋭い。リズムを乱す動きで敵を狂わせる。",
    baseStats: { hp: 38, mp: 16, atk: 12, def: 5, mat: 7, mdf: 6, spd: 15 },
    uniqueSkills: [
      {
        name: "不協和音",
        description: "敵 1 体に物理ダメージ + spd を 1 ターン -40%。",
        type: "debuff",
        element: null,
        power: 11,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元郵便配達の盗賊",
    category: "rogue",
    rank: "beginner",
    description: "町中の路地を知る、足の達人。",
    quirk: "元郵便配達",
    signatureOutfit: "革のメッセンジャーバッグ + 古い革靴 + 銀のホイッスル",
    signatureBio: "町の隅々を毎日歩き続けた者たち。誰がどの家に住み、何時に在宅するかを正確に把握している。盗賊への転身は時間の問題だった。",
    baseStats: { hp: 36, mp: 14, atk: 11, def: 5, mat: 6, mdf: 5, spd: 17 },
    uniqueSkills: [
      {
        name: "近道の知識",
        description: "次の通常攻撃が必中 + クリティカル率 +20%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 7,
        cooldown: 2,
        targetType: "self",
      },
    ],
  },
  {
    name: "元落書き屋の盗賊",
    category: "rogue",
    rank: "beginner",
    description: "夜の壁に絵を残す、芸術派の盗賊。",
    quirk: "元落書き屋",
    signatureOutfit: "色のついた指 + スプレーの皮袋 + 黒いマスク",
    signatureBio: "夜の壁に絵や名を残す癖が抜けない者たち。仕事の後にも署名を残してしまう。逮捕の半分の理由はこの癖が招く。",
    baseStats: { hp: 36, mp: 14, atk: 11, def: 5, mat: 6, mdf: 5, spd: 16 },
    uniqueSkills: [
      {
        name: "目眩ましの飛沫",
        description: "敵 1 体の命中を 2 ターン -30%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },

  // ---------- CLERIC ----------
  {
    name: "老師",
    category: "cleric",
    rank: "advanced",
    description: "300 年生きていると噂される、慈悲深い修道士。",
    quirk: "老齢",
    signatureOutfit: "白い長髭 + 木の数珠 + 紺の修道服",
    signatureBio: "実年齢は本人すら覚えていないという者たち。村の老人皆を看取り、その魂を覚えている。死者の名を呼ぶことで生者の傷を癒す独自の祈祷術を持つ。",
    baseStats: { hp: 50, mp: 28, atk: 4, def: 8, mat: 14, mdf: 14, spd: 5 },
    uniqueSkills: [
      {
        name: "古き慈悲",
        description: "味方 1 人を最大 HP の 60% まで一気に回復する。",
        type: "heal",
        element: "light",
        power: 30,
        cost: 16,
        cooldown: 4,
        targetType: "ally",
      },
    ],
  },
  {
    name: "歌う司祭",
    category: "cleric",
    rank: "intermediate",
    description: "祈りの代わりに鎮魂歌を歌う、変則派の司祭。",
    quirk: "歌好き",
    signatureOutfit: "白の祭服 + 銀の小鈴 + 五線譜の刺繍が入ったストール",
    signatureBio: "教会の合唱団から異端宣告で追放された者たち。声に乗せた祈りで死霊を浄化できる。賛美歌より民謡の節回しを好む。怒ると音域が 2 オクターブ広がる。",
    baseStats: { hp: 42, mp: 24, atk: 4, def: 6, mat: 14, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "鎮魂歌",
        description: "不死系の敵に大ダメージ。それ以外の敵には半減。",
        type: "attack",
        element: "light",
        power: 22,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "元戦士の司祭",
    category: "cleric",
    rank: "advanced",
    description: "戦場で人を殺し続けた末に祈りを学んだ司祭。",
    quirk: "元戦士",
    signatureOutfit: "古い軍剣を腰に + 白い祭服 + 戦傷の残る顔",
    signatureBio: "戦場で多くの命を奪った後、その重みに耐えかねて祈りの道に転じた者たち。剣を捨てきれず、必要な時には抜く。",
    baseStats: { hp: 50, mp: 24, atk: 8, def: 8, mat: 13, mdf: 12, spd: 6 },
    uniqueSkills: [
      {
        name: "贖罪の祈り",
        description: "敵 1 体に光属性ダメージ + 味方全員の HP を少量回復。",
        type: "attack",
        element: "light",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "沈黙派の司祭",
    category: "cleric",
    rank: "advanced",
    description: "祈りを声に出さない、瞑想型の司祭。",
    quirk: "沈黙派",
    signatureOutfit: "灰の修道服 + 数珠 + 唇に十字の入れ墨",
    signatureBio: "声を捧げる誓いを立てた者たち。祈りを心の中で唱え、その重みで奇跡を起こす。沈黙の祈りは敵に察知されにくい。",
    baseStats: { hp: 44, mp: 28, atk: 4, def: 7, mat: 14, mdf: 14, spd: 7 },
    uniqueSkills: [
      {
        name: "無音の祝福",
        description: "味方全員の HP を中量回復(敵に気付かれない)。",
        type: "heal",
        element: "light",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "童顔の司祭",
    category: "cleric",
    rank: "intermediate",
    description: "歳を重ねても少年のような顔の司祭。",
    quirk: "童顔",
    signatureOutfit: "白いベレー + 簡素な祭服 + 銀の聖印",
    signatureBio: "実年齢より遥かに若く見える者たち。敵に侮られた瞬間に祈りを発動する戦法を得意とする。子守歌で死霊を眠らせる古い儀式を継ぐ。",
    baseStats: { hp: 42, mp: 26, atk: 4, def: 6, mat: 14, mdf: 13, spd: 8 },
    uniqueSkills: [
      {
        name: "子守歌",
        description: "敵 1 体に【スタン】付与(必中)。",
        type: "debuff",
        element: "light",
        power: 0,
        cost: 11,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "雪国育ちの司祭",
    category: "cleric",
    rank: "intermediate",
    description: "雪山の修道院で育った、寒さに強い司祭。",
    quirk: "雪国育ち",
    signatureOutfit: "白熊の毛皮ストール + 紺の修道服 + 銀の十字",
    signatureBio: "雪深い修道院で生まれ育った者たち。氷点下の祈祷で精神を研ぎ澄ます。水属性の魔法に強く、寒気を癒しに転じる独自の祈祷を持つ。",
    baseStats: { hp: 46, mp: 26, atk: 4, def: 7, mat: 14, mdf: 13, spd: 6 },
    uniqueSkills: [
      {
        name: "氷脈の祈り",
        description: "味方 1 人を回復 + 1 ターン水属性耐性 +50%。",
        type: "heal",
        element: "water",
        power: 18,
        cost: 12,
        cooldown: 3,
        targetType: "ally",
      },
    ],
  },
  {
    name: "元修道女の司祭",
    category: "cleric",
    rank: "intermediate",
    description: "誓いを破って外に出た、元修道女。",
    quirk: "元修道女",
    signatureOutfit: "外套の下に修道女の黒衣 + 髪の十字結び + 銀の聖典",
    signatureBio: "厳格な修道院から逃げ出し、外で祈り続ける者たち。誓いの一部は破ったが、信仰そのものは捨てていない。罪悪感が祈りを深くする。",
    baseStats: { hp: 42, mp: 28, atk: 4, def: 6, mat: 15, mdf: 13, spd: 7 },
    uniqueSkills: [
      {
        name: "罪悪の祈り",
        description: "味方 1 人を大きく回復(自身の MP -3 の追加コスト)。",
        type: "heal",
        element: "light",
        power: 22,
        cost: 8,
        cooldown: 2,
        targetType: "ally",
      },
    ],
  },
  {
    name: "元軍医の司祭",
    category: "cleric",
    rank: "advanced",
    description: "戦場で多くを救った、軍医あがりの司祭。",
    quirk: "元軍医",
    signatureOutfit: "白い前掛け + 治癒紋の杖 + 血で汚れた包帯",
    signatureBio: "軍医として血の海を渡った者たち。退役後に司祭になり、戦場の知識を祈りに織り交ぜる。傷の処置と魔法治療の両方を同時に行う。",
    baseStats: { hp: 48, mp: 28, atk: 5, def: 7, mat: 14, mdf: 13, spd: 7 },
    uniqueSkills: [
      {
        name: "戦場の癒し",
        description: "味方全員を回復 + 状態異常 1 種を解除。",
        type: "heal",
        element: "light",
        power: 16,
        cost: 14,
        cooldown: 3,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "双子の司祭",
    category: "cleric",
    rank: "intermediate",
    description: "双子で一つの祈りを唱える、合唱型の司祭。",
    quirk: "双子",
    signatureOutfit: "対の銀の十字 + 鏡像のストール + 双子結び目の腕章",
    signatureBio: "双子で生まれ、片方の声がもう片方の祈りを補う者たち。一人での祈りは半分の力しか出ないが、双子で歌うと奇跡が二倍になる。",
    baseStats: { hp: 42, mp: 26, atk: 4, def: 6, mat: 14, mdf: 13, spd: 8 },
    uniqueSkills: [
      {
        name: "鏡像の祈り",
        description: "味方 1 人を回復、続けて同じ対象に再度回復(2 連続)。",
        type: "heal",
        element: "light",
        power: 12,
        cost: 12,
        cooldown: 3,
        targetType: "ally",
      },
    ],
  },
  {
    name: "元司書の司祭",
    category: "cleric",
    rank: "intermediate",
    description: "聖典を完璧に読み込んだ、知識派の司祭。",
    quirk: "元司書",
    signatureOutfit: "羊皮紙のロール束 + 木の眼鏡 + 紺の修道服",
    signatureBio: "教会の図書館で長く司書を務めた者たち。聖典の一文一句を完璧に覚え、状況に応じた祈りを引き出す。本人は祈りより本に親しい。",
    baseStats: { hp: 42, mp: 30, atk: 4, def: 6, mat: 16, mdf: 13, spd: 7 },
    uniqueSkills: [
      {
        name: "聖典詠唱",
        description: "味方全員の mdf +20% 2 ターン。",
        type: "buff",
        element: "light",
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "元葬儀屋の司祭",
    category: "cleric",
    rank: "intermediate",
    description: "死を見続けた末に祈りに転じた司祭。",
    quirk: "元葬儀屋",
    signatureOutfit: "黒の長衣 + 葬儀用の数珠 + 線香の小袋",
    signatureBio: "村の葬儀を取り仕切ってきた者たち。死者の魂を見送る経験から、死霊を浄化する独自の祈りを編み出した。死者の名を呼ぶことが得意。",
    baseStats: { hp: 46, mp: 26, atk: 4, def: 7, mat: 13, mdf: 14, spd: 6 },
    uniqueSkills: [
      {
        name: "送り火",
        description: "不死系の敵に大ダメージ。それ以外は半減。",
        type: "attack",
        element: "light",
        power: 22,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "裸足の司祭",
    category: "cleric",
    rank: "beginner",
    description: "靴を履かず、地に直接祈りを伝える司祭。",
    quirk: "裸足",
    signatureOutfit: "簡素な麻の修道服 + 裸足 + 木の十字",
    signatureBio: "誓いとして靴を捨て、地と直接触れ合うことを祈りの一部とする者たち。土の声を聞き、植物に祝福を与える独自の祈祷を持つ。",
    baseStats: { hp: 44, mp: 24, atk: 4, def: 7, mat: 13, mdf: 14, spd: 7 },
    uniqueSkills: [
      {
        name: "大地の祝福",
        description: "味方 1 人を回復 + 自身の def を 1 ターン +30%。",
        type: "heal",
        element: "earth",
        power: 18,
        cost: 11,
        cooldown: 3,
        targetType: "ally",
      },
    ],
  },

  // ---------- CRAFT ----------
  {
    name: "鍛冶娘",
    category: "craft",
    rank: "intermediate",
    description: "鎚を振るう手は祖父譲り、目は曾祖父譲りの鍛冶屋。",
    quirk: "頑固",
    signatureOutfit: "煤汚れた革エプロン + 一本結びの赤毛 + 重い鉄槌",
    signatureBio: "親の店を継ぐと決めた幼少から鎚を握り続けてきた者たち。村の客の名前と注文をすべて覚えている。『鉄しか信じない』と言いつつ、客への笑顔は本物。",
    baseStats: { hp: 52, mp: 12, atk: 14, def: 10, mat: 4, mdf: 6, spd: 7 },
    uniqueSkills: [
      {
        name: "一閃打ち",
        description: "渾身の一撃。クリティカル率 +50%、ヒット時に敵の def を 1 ターン -20%。",
        type: "attack",
        element: null,
        power: 16,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "蜂蜜屋の職人",
    category: "craft",
    rank: "beginner",
    description: "蜂と暮らす、甘い香りの職人。",
    quirk: "蜂蜜屋",
    signatureOutfit: "蜜蝋を塗った手袋 + 蜂の巣形の腰袋 + 黒と黄の縞のエプロン",
    signatureBio: "代々養蜂を営む家系の者たち。蜜蝋から燭台、石鹸、薬油を作る。蜂たちが朝の挨拶代わりに肩に止まる。",
    baseStats: { hp: 50, mp: 14, atk: 13, def: 9, mat: 6, mdf: 6, spd: 8 },
    uniqueSkills: [
      {
        name: "蜂蜜爆弾",
        description: "敵 1 体に物理ダメージ + spd を 2 ターン -20%。",
        type: "debuff",
        element: null,
        power: 12,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "仕立屋",
    category: "craft",
    rank: "intermediate",
    description: "服を縫う指で布を斬る、糸の職人。",
    quirk: "仕立屋",
    signatureOutfit: "胸の針山 + メジャー首巻 + 大きなハサミ",
    signatureBio: "貴族の衣装も農夫の作業着も同じ手で縫う者たち。糸の張力を読む指は、戦闘中に敵の鎧の縫い目を狙う。",
    baseStats: { hp: 50, mp: 12, atk: 13, def: 9, mat: 5, mdf: 6, spd: 8 },
    uniqueSkills: [
      {
        name: "鎧の縫い目",
        description: "敵 1 体に物理ダメージ + def を 2 ターン -25%。",
        type: "attack",
        element: null,
        power: 14,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "革職人",
    category: "craft",
    rank: "intermediate",
    description: "獣皮を読む手と短刀の使い手。",
    quirk: "革職人",
    signatureOutfit: "革のエプロン + 革ベルト 5 種 + 鞣し用の短刀",
    signatureBio: "獣を皮にする家業を継いだ者たち。革のなめし方で同じ生地でも別物の防具に化ける。獣の急所を素手で覚えている。",
    baseStats: { hp: 54, mp: 10, atk: 14, def: 11, mat: 4, mdf: 5, spd: 7 },
    uniqueSkills: [
      {
        name: "皮剥ぎ",
        description: "敵 1 体に物理ダメージ + 自身の def を 1 ターン +20%。",
        type: "attack",
        element: null,
        power: 15,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "陶工",
    category: "craft",
    rank: "beginner",
    description: "土を捏ねる手で投擲をする、独学の戦士。",
    quirk: "陶工",
    signatureOutfit: "粘土で汚れた手袋 + 焼いた壺の小袋 + 灰のエプロン",
    signatureBio: "村の窯で代々壺を焼く者たち。炎を読む目と土の質を読む手は、戦闘では投擲と火の管理に活きる。",
    baseStats: { hp: 52, mp: 12, atk: 13, def: 10, mat: 5, mdf: 6, spd: 7 },
    uniqueSkills: [
      {
        name: "焼き壺投げ",
        description: "敵 1 体に火属性ダメージ + 30% で【火傷】付与。",
        type: "attack",
        element: "fire",
        power: 13,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "製本屋",
    category: "craft",
    rank: "intermediate",
    description: "紙と糸で書を縫う、繊細な指の職人。",
    quirk: "製本屋",
    signatureOutfit: "革の作業エプロン + ピンセット + 製本糸の腕巻",
    signatureBio: "古書の修復を続ける者たち。紙の繊維を読む指は、布の縫い目を読む指と同じ。書物に挟まれた一節を必要な時に思い出す。",
    baseStats: { hp: 50, mp: 12, atk: 13, def: 10, mat: 5, mdf: 7, spd: 7 },
    uniqueSkills: [
      {
        name: "綴じの一刺し",
        description: "敵 1 体に物理ダメージ + 50% で【出血】付与。",
        type: "attack",
        element: null,
        power: 14,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "楽器作りの職人",
    category: "craft",
    rank: "intermediate",
    description: "楽器の音色を見極める、音感の職人。",
    quirk: "楽器作り",
    signatureOutfit: "音叉のペンダント + 木彫り工具のベルト + 弦の腕輪",
    signatureBio: "楽器の音を一音単位で読み分ける者たち。職人の指は弦と木の振動を扱うが、戦闘では敵の鎧の振動から急所を読む。",
    baseStats: { hp: 50, mp: 14, atk: 13, def: 9, mat: 6, mdf: 7, spd: 8 },
    uniqueSkills: [
      {
        name: "共振の一撃",
        description: "敵 1 体に物理ダメージ + 50% で【スタン】付与。",
        type: "attack",
        element: null,
        power: 13,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "機械工",
    category: "craft",
    rank: "advanced",
    description: "歯車と発条を組む、技工派の職人。",
    quirk: "機械工",
    signatureOutfit: "油で汚れた手袋 + 工具ベルト + 真鍮のゴーグル",
    signatureBio: "歯車と発条で動く機械を組む者たち。最近では戦闘用の自動装置を試作している。発明の半分は事故、残り半分は運。",
    baseStats: { hp: 54, mp: 14, atk: 15, def: 10, mat: 6, mdf: 5, spd: 7 },
    uniqueSkills: [
      {
        name: "自動装置の起動",
        description: "次の通常攻撃が 3 連撃に変化(各回威力 70%)。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "self",
      },
    ],
  },
  {
    name: "紙漉き職人",
    category: "craft",
    rank: "beginner",
    description: "水と繊維を扱う、静かな職人。",
    quirk: "紙漉き",
    signatureOutfit: "濡れた前掛け + 竹の漉き枠 + 麻紐の腕巻",
    signatureBio: "村の川辺で紙を漉き続ける者たち。水の流れを読む目で敵の動きを察する。日々の労働で得た指の力で薄物を斬る。",
    baseStats: { hp: 50, mp: 14, atk: 12, def: 9, mat: 5, mdf: 7, spd: 8 },
    uniqueSkills: [
      {
        name: "紙漉きの刃",
        description: "敵 1 体に水属性ダメージ + 自身の spd +10% 1 ターン。",
        type: "attack",
        element: "water",
        power: 13,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "染物屋",
    category: "craft",
    rank: "intermediate",
    description: "色を読む手で薬と毒を作る、化学派の職人。",
    quirk: "染物屋",
    signatureOutfit: "色とりどりの染料が付いた前掛け + 木の柄杓 + 七色の指",
    signatureBio: "布を染める家業を継いだ者たち。染料の調合は薬と毒の両方を作る。投擲の腕も鍛えている。",
    baseStats: { hp: 50, mp: 14, atk: 13, def: 9, mat: 6, mdf: 6, spd: 8 },
    uniqueSkills: [
      {
        name: "染料の罠",
        description: "敵 1 体に物理ダメージ + ランダム属性異常を 50% で付与。",
        type: "debuff",
        element: null,
        power: 12,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "鈴職人",
    category: "craft",
    rank: "beginner",
    description: "鈴の音を作る、繊細な指と耳の職人。",
    quirk: "鈴職人",
    signatureOutfit: "腰に並んだ小さな鈴 + 銀工具のベルト + 軽量な銀のエプロン",
    signatureBio: "婚礼の鈴、家畜の鈴、儀式の鈴を全て作る者たち。鈴の音色は持ち主の気を表す。戦闘では鈴を投げて敵の気を逸らす。",
    baseStats: { hp: 50, mp: 14, atk: 12, def: 9, mat: 6, mdf: 7, spd: 9 },
    uniqueSkills: [
      {
        name: "撹乱の鈴",
        description: "敵全体の命中を 1 ターン -20%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "鑿師",
    category: "craft",
    rank: "intermediate",
    description: "石と木に魂を彫る、彫刻派の職人。",
    quirk: "鑿師",
    signatureOutfit: "石粉が積もった作業着 + 鑿一式 + 木屑の指輪",
    signatureBio: "石像と木彫の両方を彫る者たち。鑿の打音は祈りの一種で、彫り出した像には魂が宿るという。実際に動き出した記録もある。",
    baseStats: { hp: 54, mp: 12, atk: 14, def: 10, mat: 5, mdf: 6, spd: 6 },
    uniqueSkills: [
      {
        name: "石割りの一撃",
        description: "敵 1 体に土属性ダメージ + 構造体系の敵に大幅特攻。",
        type: "attack",
        element: "earth",
        power: 16,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元武器商人の鍛冶屋",
    category: "craft",
    rank: "advanced",
    description: "戦場で武器を売り、自分も腕を鍛えた職人。",
    quirk: "元武器商人",
    signatureOutfit: "金属研磨剤の匂いがする外套 + 商売道具の懐 + 売り物の試し刀",
    signatureBio: "戦場の合間に武器を売り歩いた者たち。客の腕を見極めて武器を選ぶ目は、自分の戦闘技術にも還元された。",
    baseStats: { hp: 56, mp: 12, atk: 15, def: 11, mat: 4, mdf: 6, spd: 7 },
    uniqueSkills: [
      {
        name: "武器商人の目利き",
        description: "次の通常攻撃のクリティカル率 +50% + ダメージ +30%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 3,
        targetType: "self",
      },
    ],
  },

  // ---------- SUPPORT ----------
  {
    name: "旅芸人",
    category: "support",
    rank: "beginner",
    description: "笛と即興で街を巡る、根なしの楽士。",
    quirk: "風来坊",
    signatureOutfit: "赤いベレー + 木の横笛 + パッチワークのマント",
    signatureBio: "故郷を早くに出て戻らない者たち。各地で覚えた民謡を笛で演奏する。風の流れで敵の動きを読むのが特技。寝床は野原か酒場の隅。",
    baseStats: { hp: 36, mp: 22, atk: 6, def: 4, mat: 8, mdf: 8, spd: 13 },
    uniqueSkills: [
      {
        name: "風読みの笛",
        description: "味方全員の spd を 2 ターン +30%。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 10,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "子守歌の吟遊詩人",
    category: "support",
    rank: "beginner",
    description: "村の子供を寝かせる歌を覚えた、優しい吟遊詩人。",
    quirk: "子守歌",
    signatureOutfit: "綿のショール + 木のリュート + 子供の絵を描いた腕巻",
    signatureBio: "村中の子供を寝かしつけてきた者たち。歌の節回しが心を緩める力を持つと知り、戦場でも歌う道を選んだ。",
    baseStats: { hp: 36, mp: 24, atk: 5, def: 5, mat: 9, mdf: 8, spd: 13 },
    uniqueSkills: [
      {
        name: "睡魔の唄",
        description: "敵全体の spd を 2 ターン -20%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "賭博師の楽士",
    category: "support",
    rank: "intermediate",
    description: "賭場の隅で歌う、運を頼る楽士。",
    quirk: "賭博師",
    signatureOutfit: "派手なジャケット + 金の指輪 5 個 + サイコロのストラップ",
    signatureBio: "賭場で身を立てた末に楽器を抱えた者たち。歌で客を熱狂させ、酔いに乗じて金を巻き上げる。運の流れを読む目は戦闘でも生きる。",
    baseStats: { hp: 38, mp: 22, atk: 6, def: 5, mat: 8, mdf: 7, spd: 13 },
    uniqueSkills: [
      {
        name: "賭けの一振り",
        description: "ランダム効果(味方全員 atk+30% / 自身 KO / 敵 1 体スタン / 何も起きない、各 25%)。",
        type: "buff",
        element: null,
        power: 0,
        cost: 8,
        cooldown: 3,
        targetType: "self",
      },
    ],
  },
  {
    name: "占い師の旅芸人",
    category: "support",
    rank: "intermediate",
    description: "タロットと笛を持ち歩く、未来を読む楽士。",
    quirk: "占い師",
    signatureOutfit: "紫のショール + タロット束 + 銀の指輪",
    signatureBio: "村々を巡って占いと演奏で生計を立てる者たち。占い結果は半分は客の表情を読む技、もう半分は本物の予知。本人にも区別がつかない。",
    baseStats: { hp: 36, mp: 26, atk: 5, def: 5, mat: 10, mdf: 9, spd: 13 },
    uniqueSkills: [
      {
        name: "未来予知",
        description: "次のターン、味方全員の回避率 +30%。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "通訳の楽士",
    category: "support",
    rank: "intermediate",
    description: "5 ヶ国語を操る、言葉の楽士。",
    quirk: "通訳",
    signatureOutfit: "色違いの言語辞書を腰に下げ + 軽量の竪琴 + 銀のペン",
    signatureBio: "幼少期から複数の言語環境で育ち、5 ヶ国語を流暢に操る者たち。言葉の音色を歌に転用し、異国の唄を巧みに織り交ぜる。",
    baseStats: { hp: 36, mp: 24, atk: 5, def: 5, mat: 9, mdf: 8, spd: 13 },
    uniqueSkills: [
      {
        name: "異国の唄",
        description: "敵 1 体に【混乱】を 60% で付与。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "動物使いの吟遊詩人",
    category: "support",
    rank: "intermediate",
    description: "犬や鳩と一緒に旅する、動物の友。",
    quirk: "動物使い",
    signatureOutfit: "鳥籠ペンダント + 犬笛 + 動物の毛が付いた外套",
    signatureBio: "幼少から動物に懐かれる体質の者たち。犬と鳩を連れて旅し、歌に動物の鳴き声を混ぜる独自の演奏を編み出した。",
    baseStats: { hp: 38, mp: 22, atk: 6, def: 5, mat: 9, mdf: 8, spd: 12 },
    uniqueSkills: [
      {
        name: "鳥使いの呼び声",
        description: "敵 1 体に風属性ダメージ + 命中 -30% 1 ターン。",
        type: "attack",
        element: "wind",
        power: 12,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "観光案内の楽士",
    category: "support",
    rank: "beginner",
    description: "街の小道を歌で案内する、地理の楽士。",
    quirk: "観光案内",
    signatureOutfit: "色とりどりの旗 + 笛 + 名所の絵が刺繍された外套",
    signatureBio: "観光客を歌で案内する者たち。土地の伝説を歌に編み、それが物語を生む。地理に詳しく、戦闘では地形を活かす。",
    baseStats: { hp: 36, mp: 22, atk: 5, def: 5, mat: 8, mdf: 8, spd: 14 },
    uniqueSkills: [
      {
        name: "地形の歌",
        description: "味方全員の spd +20% 2 ターン。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 10,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "葬儀の楽士",
    category: "support",
    rank: "intermediate",
    description: "葬儀で歌う、鎮魂派の楽士。",
    quirk: "葬儀屋",
    signatureOutfit: "黒の外套 + 黒い旋律の笛 + 線香を腰に",
    signatureBio: "村々の葬儀で歌うことを生業とする者たち。死者を送る歌の節回しは、生者の傷を癒すこともある。陰気だが、招かれる場所は多い。",
    baseStats: { hp: 36, mp: 26, atk: 5, def: 5, mat: 9, mdf: 9, spd: 12 },
    uniqueSkills: [
      {
        name: "送葬の歌",
        description: "不死系の敵に大ダメージ + 味方全員の HP を少量回復。",
        type: "attack",
        element: "light",
        power: 18,
        cost: 12,
        cooldown: 3,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "産婆の楽士",
    category: "support",
    rank: "intermediate",
    description: "出産の場で歌う、命を迎える楽士。",
    quirk: "産婆",
    signatureOutfit: "白い前掛け + 木の竪琴 + 子供の名前を刺繍した帽子",
    signatureBio: "村の出産に立ち会い続ける者たち。母親に歌いかけて陣痛を和らげる節を持つ。命の始まりに立ち会う仕事は戦場の癒しにも応用される。",
    baseStats: { hp: 38, mp: 24, atk: 5, def: 6, mat: 9, mdf: 9, spd: 12 },
    uniqueSkills: [
      {
        name: "命の歌",
        description: "味方 1 人を中量回復 + 状態異常 1 種を解除。",
        type: "heal",
        element: "light",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "ally",
      },
    ],
  },
  {
    name: "公証人の楽士",
    category: "support",
    rank: "intermediate",
    description: "契約と歌を扱う、論理派の楽士。",
    quirk: "公証人",
    signatureOutfit: "羊皮紙の束 + 黒インクの指 + 銀のペン",
    signatureBio: "契約書の作成を生業としつつ、歌でも生計を立てる者たち。法の言葉を歌に転用し、敵の動きに『契約』を結びつける。",
    baseStats: { hp: 36, mp: 24, atk: 5, def: 5, mat: 9, mdf: 8, spd: 13 },
    uniqueSkills: [
      {
        name: "契約の縛り",
        description: "敵 1 体の spd を 2 ターン -50%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 11,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "仲介屋の楽士",
    category: "support",
    rank: "intermediate",
    description: "売買の間に立つ、口の達者な楽士。",
    quirk: "仲介屋",
    signatureOutfit: "細身の外套 + 商売道具の懐 + 銀のペンダント",
    signatureBio: "貴族と平民の間に立って商売を取り持つ者たち。話術と即興の歌で空気を変え、争いを止める。戦闘では言葉で敵を懐柔する。",
    baseStats: { hp: 36, mp: 22, atk: 5, def: 5, mat: 8, mdf: 8, spd: 14 },
    uniqueSkills: [
      {
        name: "和議の唄",
        description: "敵 1 体の atk を 2 ターン -25%。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 10,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "酔いどれ吟遊詩人",
    category: "support",
    rank: "beginner",
    description: "酒を片手に歌う、軽い口調の楽士。",
    quirk: "酔いどれ",
    signatureOutfit: "酒瓶の腰下げ + 赤い鼻 + 古いリュート",
    signatureBio: "酒場の隅で歌う者たち。酔いに任せた即興は時に天才的、時にひどい。聴衆は両方を許す。",
    baseStats: { hp: 38, mp: 22, atk: 6, def: 5, mat: 8, mdf: 7, spd: 12 },
    uniqueSkills: [
      {
        name: "酔いの一節",
        description: "敵 1 体に【混乱】を 50% で付与 + 自身の atk +15% 1 ターン。",
        type: "debuff",
        element: null,
        power: 0,
        cost: 9,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },

  // ---------- HERETIC ----------
  {
    name: "禁書館の番人",
    category: "heretic",
    rank: "advanced",
    description: "封印された書庫で長年過ごした、口数の少ない者。",
    quirk: "無口",
    signatureOutfit: "灰の髪 + 鎖で繋がれた古書 + 黒い手袋",
    signatureBio: "幼い頃に禁書館に閉じ込められ、長い年月を経てようやく外に出された者たち。そこで読んだ書物の半分は、世界の常識を裏返すような内容だった。語ろうとすると舌が痛むという。",
    baseStats: { hp: 38, mp: 30, atk: 4, def: 6, mat: 16, mdf: 12, spd: 7 },
    uniqueSkills: [
      {
        name: "封じの一節",
        description: "敵の特技 CD を倍化（次の特技まで延長）。",
        type: "debuff",
        element: "dark",
        power: 0,
        cost: 14,
        cooldown: 5,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元神官の異端者",
    category: "heretic",
    rank: "advanced",
    description: "教義を否定して追放された、元神官。",
    quirk: "元神官",
    signatureOutfit: "破られた祭服 + 逆さの十字 + 黒インクの聖典",
    signatureBio: "教団の偽善に気付き、教義を否定して追放された者たち。祈りの言葉を呪詛に転用する技を持つ。元同僚を見ると目を逸らす。",
    baseStats: { hp: 40, mp: 30, atk: 4, def: 6, mat: 16, mdf: 13, spd: 7 },
    uniqueSkills: [
      {
        name: "逆位の祈り",
        description: "敵 1 体に光属性ダメージ + 命中 -30% 2 ターン。",
        type: "attack",
        element: "light",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "双頭の異端者",
    category: "heretic",
    rank: "legendary",
    description: "二つの頭が常に矛盾する、異形の異端者。",
    quirk: "双頭",
    signatureOutfit: "首 2 本通る黒衣 + 双子用の儀式刀 + 銀の輪 4 つ",
    signatureBio: "生まれつき双頭の異端者たち。互いに異なる思想を持ち、議論しながら戦う。意見が一致した瞬間に強大な術が発動する。",
    baseStats: { hp: 42, mp: 34, atk: 5, def: 7, mat: 18, mdf: 14, spd: 8 },
    uniqueSkills: [
      {
        name: "双論の合致",
        description: "敵全体に闇属性ダメージ + 30% で【沈黙】付与。",
        type: "attack",
        element: "dark",
        power: 14,
        cost: 16,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "不死研究の異端者",
    category: "heretic",
    rank: "advanced",
    description: "永遠の命を求めて禁忌に踏み込んだ研究者。",
    quirk: "不死研究",
    signatureOutfit: "腐敗の匂いがする外套 + 死体の図解集 + 黒い手袋",
    signatureBio: "禁忌の研究で死霊を扱う者たち。本人たちは『死後の世界の地図を作っているだけ』と言うが、教団は許さない。",
    baseStats: { hp: 36, mp: 32, atk: 4, def: 6, mat: 17, mdf: 12, spd: 7 },
    uniqueSkills: [
      {
        name: "死者の呼び声",
        description: "敵 1 体に闇属性ダメージ + 50% で【呪い化】付与。",
        type: "debuff",
        element: "dark",
        power: 13,
        cost: 13,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "言語学者の異端者",
    category: "heretic",
    rank: "advanced",
    description: "禁じられた言語を使う、言葉の研究者。",
    quirk: "言語学者",
    signatureOutfit: "古文字の刺繍された外套 + 古代の杖 + 文字の入れ墨",
    signatureBio: "失われた言語、禁じられた言語を研究する者たち。言葉そのものに力があると信じ、口にした瞬間に術が発動する。",
    baseStats: { hp: 38, mp: 30, atk: 4, def: 6, mat: 16, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "禁字呪",
        description: "敵 1 体に必中の闇属性ダメージ + 【沈黙】付与。",
        type: "debuff",
        element: "dark",
        power: 14,
        cost: 13,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "解剖学者の異端者",
    category: "heretic",
    rank: "advanced",
    description: "生命の構造を解剖で読み解く、禁忌の医者。",
    quirk: "解剖学者",
    signatureOutfit: "白衣の上に黒の外套 + 解剖刀 + 解剖図のロール",
    signatureBio: "教義に反して解剖を行い、追放された医者たち。生命の構造を熟知し、急所を狙う技は鋭い。",
    baseStats: { hp: 40, mp: 28, atk: 5, def: 6, mat: 15, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "解剖の刃",
        description: "敵 1 体に物理ダメージ + 50% で【出血】付与。",
        type: "attack",
        element: null,
        power: 17,
        cost: 11,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "元盗賊王の異端者",
    category: "heretic",
    rank: "legendary",
    description: "裏社会で頂点に立った末に、魔導の道に転じた異端者。",
    quirk: "元盗賊王",
    signatureOutfit: "金の指輪 7 個 + 黒い長衣 + 細身の魔導刀",
    signatureBio: "裏社会で頂点まで上り詰めた末に、その栄光に飽きて魔導の道に転じた者たち。盗賊の技と魔法を組み合わせる独自の流派を編み出した。",
    baseStats: { hp: 42, mp: 34, atk: 6, def: 7, mat: 17, mdf: 13, spd: 9 },
    uniqueSkills: [
      {
        name: "影盗み",
        description: "敵 1 体の MP を奪う(自身に MP +10、敵 -10)。",
        type: "debuff",
        element: "dark",
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "言葉狂いの異端者",
    category: "heretic",
    rank: "intermediate",
    description: "言葉そのものに憑かれた、奇妙な異端者。",
    quirk: "言葉狂い",
    signatureOutfit: "言葉が縫い付けられた外套 + 自分の声を録音した小箱 + 銀のペン",
    signatureBio: "ある日突然、言葉そのものに取り憑かれた者たち。話す言葉が現実を歪める力を持つようになり、教団から異端認定された。",
    baseStats: { hp: 38, mp: 30, atk: 4, def: 5, mat: 16, mdf: 11, spd: 7 },
    uniqueSkills: [
      {
        name: "言葉の現実化",
        description: "敵 1 体に魔法ダメージ + ランダム属性異常を 60% で付与。",
        type: "debuff",
        element: null,
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "異界帰還の異端者",
    category: "heretic",
    rank: "legendary",
    description: "異界から戻った後、人と話さなくなった魔導師。",
    quirk: "異界帰還",
    signatureOutfit: "黒い半透明の外套 + 異界の文字が浮かぶ杖 + 銀の額飾り",
    signatureBio: "ある日忽然と消え、半年後に戻ってきた者たち。記憶の半分は欠けているが、その代わりに異界の魔法を持ち帰った。",
    baseStats: { hp: 42, mp: 34, atk: 5, def: 7, mat: 18, mdf: 14, spd: 8 },
    uniqueSkills: [
      {
        name: "異界の召喚",
        description: "敵全体に闇属性ダメージ + ランダム異常を 30% で付与。",
        type: "attack",
        element: "dark",
        power: 16,
        cost: 16,
        cooldown: 5,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "影使いの異端者",
    category: "heretic",
    rank: "advanced",
    description: "影を物理的に操る、闇魔法の使い手。",
    quirk: "影使い",
    signatureOutfit: "黒のフード + 黒の手袋 + 自分の影が肥大した第二の輪郭",
    signatureBio: "影を意のままに操る者たち。自分の影を伸ばして敵を絡め取る。光が無いと魔法が使えないが、月光や星明かりでも十分。",
    baseStats: { hp: 40, mp: 30, atk: 4, def: 6, mat: 16, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "影の縛り",
        description: "敵 1 体に闇属性ダメージ + 60% で【スタン】付与。",
        type: "attack",
        element: "dark",
        power: 13,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "自閉派の異端者",
    category: "heretic",
    rank: "intermediate",
    description: "他人と関わらず、塔に籠もる魔導の探究者。",
    quirk: "自閉派",
    signatureOutfit: "顔を覆う仮面 + 灰の長衣 + 自作の杖",
    signatureBio: "他人と関わることを避け、塔に籠もって魔導を研究する者たち。教団の検閲を受けず、独自の流派を発展させ、結果として異端認定される。",
    baseStats: { hp: 36, mp: 32, atk: 4, def: 5, mat: 17, mdf: 11, spd: 7 },
    uniqueSkills: [
      {
        name: "孤独の防壁",
        description: "自身の mdf +50% 2 ターン + 敵の対象から外れる 1 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 12,
        cooldown: 4,
        targetType: "self",
      },
    ],
  },
  {
    name: "元魔導院追放の異端者",
    category: "heretic",
    rank: "advanced",
    description: "魔導院から追放された後、独自の流派を立てた魔導師。",
    quirk: "元魔導院追放",
    signatureOutfit: "破かれた魔導院の制服 + 杖の残骸 + 焼け跡の指輪",
    signatureBio: "魔導院で何かしらの規則を破り、追放された者たち。失った地位の代わりに、自分の流派を作る自由を得た。",
    baseStats: { hp: 40, mp: 32, atk: 5, def: 6, mat: 17, mdf: 12, spd: 8 },
    uniqueSkills: [
      {
        name: "破門の一撃",
        description: "敵 1 体に魔法ダメージ + 50% で【火傷】付与。",
        type: "attack",
        element: "fire",
        power: 16,
        cost: 11,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },

  // ---------- RARE ----------
  {
    name: "星詠み",
    category: "rare",
    rank: "legendary",
    description: "星の運行から運命を読む、北方の予言者。",
    quirk: "夜行性",
    signatureOutfit: "銀糸の刺繍が入った藍色の外套 + 星座盤 + 銀の指輪 7 つ",
    signatureBio: "生まれた瞬間に天空に新しい星が現れたと語られる者たち。本人たちは否定するが、彼らの通った道では雨が止む現象が観測されている。星辰の力を借りて戦況そのものを書き換える。",
    baseStats: { hp: 40, mp: 36, atk: 4, def: 6, mat: 18, mdf: 14, spd: 9 },
    uniqueSkills: [
      {
        name: "星辰の指針",
        description: "次のターン、味方全員の与ダメージ +25%、被ダメージ -15%。",
        type: "buff",
        element: "light",
        power: 0,
        cost: 18,
        cooldown: 5,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "半妖精の魔法使い",
    category: "rare",
    rank: "legendary",
    description: "妖精と人の間に生まれた、二つの世界を持つ者。",
    quirk: "半妖精",
    signatureOutfit: "尖った耳 + 半透明の翅 + 銀糸の編み込み外套",
    signatureBio: "妖精と人の間に生まれた者たち。両方の世界が見え、両方の言葉を話す。長寿だが、どちらの社会にも完全には属せない孤独を背負う。",
    baseStats: { hp: 42, mp: 38, atk: 5, def: 6, mat: 19, mdf: 14, spd: 11 },
    uniqueSkills: [
      {
        name: "妖精郷の囁き",
        description: "敵全体に風属性ダメージ + 自身の spd +20% 2 ターン。",
        type: "attack",
        element: "wind",
        power: 14,
        cost: 14,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "龍の子",
    category: "rare",
    rank: "legendary",
    description: "龍と人の間に生まれた、鱗を持つ稀代の魔法使い。",
    quirk: "龍の子",
    signatureOutfit: "頬の銀の鱗 + 黒い長衣 + 龍紋の指輪",
    signatureBio: "古き龍と人の女の間に生まれた者たち。鱗が頬に残り、息は時に火を伴う。本人たちは普通の人として生きたいが、龍の血が許さない。",
    baseStats: { hp: 44, mp: 36, atk: 6, def: 7, mat: 18, mdf: 14, spd: 9 },
    uniqueSkills: [
      {
        name: "龍息",
        description: "敵全体に火属性ダメージ + 30% で【火傷】付与。",
        type: "attack",
        element: "fire",
        power: 16,
        cost: 16,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
  {
    name: "古竜の血を引く者",
    category: "rare",
    rank: "legendary",
    description: "数代前に龍と交わった家系の、稀代の魔法使い。",
    quirk: "古竜の血",
    signatureOutfit: "銀の鱗で縁取られた外套 + 龍の牙のペンダント + 朱の眼帯",
    signatureBio: "数代前の祖先に古竜が混じる家系の者たち。普段は人だが、感情が高ぶると瞳孔が縦に裂ける。古龍の記憶が時々頭をよぎる。",
    baseStats: { hp: 42, mp: 38, atk: 5, def: 7, mat: 20, mdf: 15, spd: 9 },
    uniqueSkills: [
      {
        name: "龍血の覚醒",
        description: "自身の mat +30% / atk +20% 2 ターン。",
        type: "buff",
        element: null,
        power: 0,
        cost: 18,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "月光の魔法使い",
    category: "rare",
    rank: "advanced",
    description: "月の光を魔法に変換する、夜の魔法使い。",
    quirk: "月光",
    signatureOutfit: "銀色のローブ + 三日月の額飾り + 月光石の杖",
    signatureBio: "月の光に当たることで魔力を充填する者たち。日中は弱いが、夜には別人のように強くなる。月のない日は普通の魔法使い。",
    baseStats: { hp: 40, mp: 36, atk: 4, def: 6, mat: 18, mdf: 13, spd: 9 },
    uniqueSkills: [
      {
        name: "月光の刃",
        description: "敵 1 体に必中の光属性ダメージ + 命中 -20% 1 ターン。",
        type: "attack",
        element: "light",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "星詠み二世",
    category: "rare",
    rank: "legendary",
    description: "先代の星詠みの弟子、独自の流派を創りつつある若き星見。",
    quirk: "星詠み2世",
    signatureOutfit: "新月色の外套 + 改良型の星座盤 + 銀のペンダント",
    signatureBio: "先代の星詠みに師事しながら、独自の星辰流派を創ろうとする者たち。先代を尊敬しつつも、新しい星座の解釈に挑戦している。",
    baseStats: { hp: 40, mp: 36, atk: 4, def: 6, mat: 18, mdf: 14, spd: 10 },
    uniqueSkills: [
      {
        name: "新星の予兆",
        description: "次のターン、味方全員の与ダメージ +20%、自身のクリ率 +30%。",
        type: "buff",
        element: "light",
        power: 0,
        cost: 16,
        cooldown: 5,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "風使い",
    category: "rare",
    rank: "advanced",
    description: "風を物理的に操る、空気の魔法使い。",
    quirk: "風使い",
    signatureOutfit: "風で揺れる薄絹のローブ + 透明な杖 + 鳥の羽の指輪",
    signatureBio: "幼少から風と意思疎通できる者たち。風を撫でて空気の流れを変え、敵の矢を逸らし、自分の歩みを軽くする。",
    baseStats: { hp: 40, mp: 34, atk: 4, def: 6, mat: 17, mdf: 13, spd: 11 },
    uniqueSkills: [
      {
        name: "風の盾",
        description: "味方全員の回避率 +25% 2 ターン。",
        type: "buff",
        element: "wind",
        power: 0,
        cost: 14,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "水脈読み",
    category: "rare",
    rank: "advanced",
    description: "地下の水脈を感知する、独自の地理派魔法使い。",
    quirk: "水脈読み",
    signatureOutfit: "青い長衣 + 水晶の杖 + 水脈図のペンダント",
    signatureBio: "地下を流れる水脈を肌で感じる者たち。水を呼び寄せ、戦闘中も水属性魔法を強化する。乾燥した地では普通より弱い。",
    baseStats: { hp: 40, mp: 36, atk: 4, def: 6, mat: 18, mdf: 14, spd: 9 },
    uniqueSkills: [
      {
        name: "湧水の刃",
        description: "敵 1 体に水属性ダメージ + 50% で【出血】付与。",
        type: "attack",
        element: "water",
        power: 16,
        cost: 12,
        cooldown: 3,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "竜眼の魔法使い",
    category: "rare",
    rank: "legendary",
    description: "瞳孔が縦に割れた、竜の眼を持つ魔法使い。",
    quirk: "竜眼",
    signatureOutfit: "黒の眼帯(片目だけ) + 銀の長衣 + 竜の鱗を縫い込んだ手袋",
    signatureBio: "瞳孔が縦に割れている者たち。普通の眼では見えない魔力の流れを直接見る。両眼を開くと魔力に酔って気絶することがある。",
    baseStats: { hp: 42, mp: 36, atk: 5, def: 7, mat: 19, mdf: 15, spd: 10 },
    uniqueSkills: [
      {
        name: "竜眼の凝視",
        description: "敵 1 体に必中の闇属性ダメージ + 弱点公開 2 ターン。",
        type: "attack",
        element: "dark",
        power: 14,
        cost: 14,
        cooldown: 4,
        targetType: "enemy",
      },
    ],
  },
  {
    name: "妖精郷育ちの魔法使い",
    category: "rare",
    rank: "legendary",
    description: "妖精郷で育てられた、人型の妖精のような者。",
    quirk: "妖精郷育ち",
    signatureOutfit: "光沢のある絹のローブ + 蔓と花の冠 + 透明な杖",
    signatureBio: "幼少期を妖精郷で過ごした者たち。普通の人より老化が遅く、感情のあり方も妖精寄り。人間社会への馴染みは浅い。",
    baseStats: { hp: 40, mp: 38, atk: 4, def: 6, mat: 19, mdf: 14, spd: 11 },
    uniqueSkills: [
      {
        name: "妖精の祝福",
        description: "味方全員の HP を中量回復 + 状態異常 1 種を解除。",
        type: "heal",
        element: "light",
        power: 18,
        cost: 16,
        cooldown: 4,
        targetType: "all_allies",
      },
    ],
  },
  {
    name: "不死者の血族",
    category: "rare",
    rank: "legendary",
    description: "祖先に不死者を持つ、寿命の長い魔法使い。",
    quirk: "不死者",
    signatureOutfit: "白い肌 + 黒の長衣 + 古い銀の指輪",
    signatureBio: "祖先に不死者を持つ家系の者たち。本人たちは死ぬが、寿命は普通より 50 年長い。墓場に近い場所で力が増す。",
    baseStats: { hp: 44, mp: 34, atk: 5, def: 7, mat: 17, mdf: 14, spd: 8 },
    uniqueSkills: [
      {
        name: "不死の血",
        description: "自身を即座に最大 HP の 70% まで回復 + 状態異常を全て解除。",
        type: "heal",
        element: "dark",
        power: 0,
        cost: 18,
        cooldown: 5,
        targetType: "self",
      },
    ],
  },
  {
    name: "彗星の使者",
    category: "rare",
    rank: "legendary",
    description: "彗星が空を渡る瞬間に生まれた、稀代の魔法使い。",
    quirk: "彗星",
    signatureOutfit: "尾を引く銀色の外套 + 流星紋の杖 + 蒼い眼",
    signatureBio: "彗星が地平線を渡る瞬間に生まれた者たち。誕生時の宇宙の音を聞いたと言うが、本人にも記憶は曖昧。瞳の奥に流星の軌跡が残る。",
    baseStats: { hp: 40, mp: 38, atk: 5, def: 6, mat: 20, mdf: 14, spd: 10 },
    uniqueSkills: [
      {
        name: "流星の落下",
        description: "敵全体に光属性ダメージ + 自身の MP -5 (追加コスト)。",
        type: "attack",
        element: "light",
        power: 18,
        cost: 14,
        cooldown: 4,
        targetType: "all_enemies",
      },
    ],
  },
];
